#!/usr/bin/env bash
# This script displays a list of currently running processes

echo "USER       PID  PPID  COMMAND"

# Use the ps command to list all processes for all users
ps axo user,pid,ppid,command | awk '{printf "%-10s %5d %5d %s\n",$1,$2,$3,$4}' | less

