#!/usr/bin/env bash
# This script stops the infinity.sh process

# Find the PID of the infinity.sh process
pid=$(pgrep -f 4-to_infinity_and_beyond)

# If the PID is found, kill the process
if [ -n "$pid" ]; then
  kill "$pid"
  echo "Stopped 4-to_infinity_and_beyond process with PID $pid"
else
  echo "4-to_infinity_and_beyond process not found"
fi
