#!/usr/bin/env bash

# This script stops the process named "4-to_infinity_and_beyond" using pkill command

# pkill -15 "bash ./4-to_infinity_and_beyond" -f

# OR

pkill -f "4-to_infinity_and_beyond"

