#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely with a sleep 2 in between each iteration
# It also displays "I am invincible!!!" when receiving a SIGTERM signal

# Handle SIGTERM
trap "echo 'I am invincible!!!'" 15

# trap "echo I am invincible!!!" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
