#!/usr/bin/env bash
# This script displays number from 1-20 and:

number=1

while [ "$number" -le 20 ]; do
    echo "$number"
    case "$number" in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
            ;;
    esac
    ((number++))
done
