#!/usr/bin/env bash
# This script displays the content of the current directory in list format, only the part of the name after the first dash is displayed

hour=0

while [ $hour -le 12 ]; do
    minute=1
    while [ $minute -le 59 ]; do
        printf "%02d:%02d\n" "$hour" "$minute"
        ((minute++))
    done
    ((hour++))
done
